#! /bin/bash
# Script to ease common apt commands
#
# Usage: {script-name} [ upd | upg | dist | rem | ins <package-name> ]
#
# Short forms
#   1. upd  - u
#   2. upg  - U
#   3. dist - d
#   4. rem  - r
#   5. ins  - i

# Source the common functions
. ./common-script

# Function to execute apt-get command
execute_apt() {
  if [ $# -lt 1 ]
  then
    error $FUNCTION_ERR_MSG
  fi

  # check if user is root and execut command accordingly
  if root_check
  then
    apt-get $@
  else
    sudo apt-get $@
  fi
}

case "$1" in
  "upd" | "u")
     # Update Package lists
     execute_apt update
     ;;

  "upg" | "U")
     # Update Package lists and Upgrade Packages
     execute_apt update && execute_apt upgrade
     ;;

  "dist" | "d")
     # Update Package lists and Perform dist-upgrade
     execute_apt update && execute_apt dist-upgrade
     ;;

  "rem" | "r")
     # Remove unwanted packages
     execute_apt autoremove
     ;;

  "ins" | "i")
     # Install package(s) specified after option
     if [ $# -lt 2 ]
     then
       print_usage "ins <package_name>"
     fi
     #  packages=`extract_packages "$*"`

     # shift by one parameter to get the list of packages
     shift
     execute_apt "install $@"
     ;;

  *)
     # Print usage method
     print_usage
esac
