#! /bin/bash
# Script that is to be used for generating backups
# and updating the backup of current directory
#
# Customizable environment variables
#   DEST - the destination archive including archive name
#          (defaults to custom used media device)
#
#   In case the archive is an external media you could
#   use the variable below to specify the archive,
#   MEDIA_NAME   - name of the media device
#                  (defaults to 'unique')
#   ARCHIVE_NAME - the name of the archive in the media device
#                  (defaults to 'Library(bzipped, backup).zip')
#
#   USE_IGNORES  - use '.exclude.lst' as ignore file for zip

if test -z "$DEST"
then
  # Define media name to be the name of the device
  # I oftne use unless it's defined
  if test -z "$MEDIA_NAME"
  then
    MEDIA_NAME='unique'
  fi

  # Define archive name to be the default name that
  # used initially unless it's defined
  if test -z "$ARCHIVE_NAME"
  then
    ARCHIVE_NAME='Library(bzipped, backup).zip'
  fi

  DEST="/media/${USER}/${MEDIA_NAME}/${ARCHIVE_NAME}"
fi

EXISTING_OR_NEW_BACKUP="$DEST"
TAR_IGNORE_FILE='.ignore.lst'
ZIP_IGNORE_FILE='.exclude.lst'

# Creation works but 'updation' seems to add files that
# are ignored
#
# Updation is designed to not work with 'compression'
# tar cvf ${EXISTING_OR_NEW_BACKUP} --exclude-ignore='.ignore.lst' .

# Cannot be used to update
# tar cf - . | zip -Z bzip2 backup -

# Avoid including ignores if requested
if test -n "$USE_IGNORES"
then
  other_opts="-x@${ZIP_IGNORE_FILE} "
fi

# Creation and updation works with compression fo 'zip'
zip -v -u $other_opts -Z bzip2 "${EXISTING_OR_NEW_BACKUP}" -r .
