#! /bin/bash
# Script that installs essential packages throug apt-get package manager
#
# Usage: {script-name}

. ./common-script

# Use the apt-script to install packages
require './apt-script'

dict_packages='dict dict-gcide dict-wn'
essential_packages="$dict_packages git vim zeal gparted redshift tlp pm-utils g++"
optional_packages='openjdk-8-jdk-headless xserver-xorg-input-libinput clang-4.0 vlc chromium'

echo 'The current list of ESSENTIAL packages are:'
for package in $essential_packages
do
  echo '* '"$package"
done

echo
echo 'The current list of OPTIONAL packages are:'
for package in $optional_packages
do
  echo '* '"$package"
done

echo
if [ "$1" == 'opt' ] || [ "$1" == "o" ]
then
  notify 'Installing both essential and optional packages...'
  ./apt-script ins $essential_packages $optional_packages
else
  notify 'Installing ONLY the essential packages...'
  ./apt-script ins $essential_packages
fi
