#! /bin/bash
# Script that installs essential packages throug apt-get package manager
#
# Usage: {script-name}
#
# Required packages
required_packages="git vim gparted openjdk-8-jdk-headless"

echo "The current list of packages in required list are :"
echo -e "\n\t\t$required_packages\n"
echo -e "Installing the above packages... \n" 

sudo apt-get update && sudo apt-get install $required_packages
