#! /bin/bash
# Script that installs essential packages throug apt-get package manager
#
# Usage: {script-name}

. ./common

# Use the apt-script to install packages
require "./apt-script"

# Required packages
dict_packages="dict dict-gcide dict-wn"
required_packages="git vim gparted openjdk-8-jdk-headless $dict_packages"

echo "The current list of packages in required list are :"
echo -e "\n\t\t$required_packages\n"
echo -e "Installing the above packages... \n" 

./apt-script ins $required_packages
