#! /bin/bash
# Script that installs essential packages throug apt-get package manager
#
# Usage: {script-name}

. ./common-script

# Use the apt-script to install packages
require './apt-script'

dict_packages='dict dict-gcide dict-wn'
essential_packages="$dict_packages git vim zeal gparted redshift tlp pm-utils g++ keepassxc"
optional_packages='openjdk-9-jdk-headless clang-4.0 vlc chromium ri pidgin git-email homebank lifeograph'

echo 'The current list of ESSENTIAL packages are:'
for package in $essential_packages
do
  echo '* '"$package"
done

packages_to_install="$essential_packages"

# Get the prefernece for optional packages
echo # Kept for new-line (side-effect)
echo 'Choose the optional packages to install:'

for package in $optional_packages
do
  while true
  do
    echo -n "Do you want to install '$package' [y/n]: "
    read yn
    case $yn in
      [Yy]*)
        optional_packages_to_install+=" $package"
        break
        ;;
      [Nn]*)
        break
        ;;
      *)
        echo 'Please answer yes or no.'
        ;;
    esac
  done
done

packages_to_install+="$optional_packages_to_install"

echo # Kept for new line (side-effect)
notify 'Installing the following packages:'
for package in $packages_to_install
do
  echo '* '"$package"
done

./apt-script ins $packages_to_install
