#! /bin/bash

# Required packages
required_packages="git vim gparted"

echo "The current list of packages in required list are :"
echo -e "\n\t\t$required_packages\n"
echo -e "Installing the above packages... \n" 

sudo apt-get update && sudo apt-get install $required_packages




# Install external packages (packages not available through apt)
# Create a directory (if it doesn't exist)  to store the package
# Local location of downloaded packages
package_location=$(pwd)/packages

# Remote Location of packages
atom_url="https://atom.io/download/deb"
tomcat_url="http://mirror.fibergrid.in/apache/tomcat/tomcat-9/v9.0.0.M21/bin/apache-tomcat-9.0.0.M21.tar.gz"
tomcat_sign_url="http://mirror.fibergrid.in/apache/tomcat/tomcat-9/v9.0.0.M21/bin/apache-tomcat-9.0.0.M21.tar.gz.pgp" 


# Start the required work

mkdir packages 2> /dev/null

if [ $# -ne 1 ]
then
  echo -e "\n\t\tNo external package will be installed (non requested)\n"
  exit
fi

if [ "$1" == "all" ]
then 
  atom_install=1
  tomcat_install=1
elif [ "$1" == "atom" ]
then
  atom_install=1
elif [ "$1" == "tomcat" ]
then
  tomcat_install=1
fi

# Install atom editor if required
if [ $atom_install ]
then
  echo -e "\n\t\tInstalling Atom Editor\n"
  wget "$atom_url" -O $package_location/atom.deb &&
  sudo dpkg -i $package_location/atom.deb
fi

# TODO Verify signature and install
# Install Tomcat if required (assumed to be in .tar.gz formt)
# Installation done to opt directory
if [ $tomcat_install ]
then
  echo -e "\n\t\tInstalling Tomcat\n"
  wget $tomcat_url -O $package_location/tomcat.tar.gz &&
  cd /opt &&
  tar -xzf $package_location/tomcat.tar.gz
  # wget http://mirror.fibergrid.in/apache/tomcat/tomcat-9/v9.0.0.M21/bin/apache-tomcat-9.0.0.M21.tar.gz.pgp 
fi
