#! /bin/bash
# Script that copies all the files ending with "-script" in working directory
# and copies them to the the "$HOME/.local/bin" directory

# TODO
# 1. Find way to check if the "$HOME/.local/bin" directory is in PATH and add it to PATH if not

IDENTIFIER="-script"
scripts=`ls | grep -e "$IDENTIFIER"`

# Create the DESTINATION directory if it doesn't exist
# Else silent failure
DESTINATION="$HOME/.local/bin"
mkdir -p $DESTINATION

for script in $scripts
do
  if [ "$script" != "common-script" ]
  then
    dest_file_name=`echo $script | tr a-z A-Z`
  else
    dest_file_name=$script
  fi

  cp $script $DESTINATION/$dest_file_name
done
echo "Script installation successful!"
