#! /bin/bash
#
# Sync the backup Git repos with their upstreams.
#
# The upstream is generally assumed to be the repo in which this
# script is placed.
#
# It is assumed that it is always possible to fast-forward the history of
# the "backup" repo. IOW, it is assumed that it is only a "backup" of the upstream
# and not a fork in which changes are made.

# Can be installed using lxconf-bash/script-config
. COMMON-SCRIPT

# Specify the external repos as a shell array and remove the
# following line.
error "Backup repos not specified"

# Example,
# backup[1]='/media/unique/unique/Documents'
# backup[2]='/media/unique/disk/Documents'
# backup[3]='/media/unique/Memory Card/Documents'
# backup_num=3

for i in `seq $backup_num`
do
	if test -d "${backup[i]}"
	then
		notify "Updating '${backup[i]}'"
		(cd "${backup[i]}" && git pull) || error "Could not sync backups !!!"
	else
		notify "'${backup[i]}' not found"
	fi
done
