#! /bin/bash
# Script that customises Vim for personal needs
# Currently it sets functionality for converting tab to spaces
#
# Usage: {script-name}

. ./common-script

# Recommended  addition to .vimrc
# Due to presence of defaults.vim
# See ":help defaults.vim"
# Doesn't work for version less than 8
defaults_addition='unlet! skip_defaults_vim\nsource $VIMRUNTIME/defaults.vim'

# Variables for configuration
# Number of space to insert when hitting <Tab> in all places
# If smarttab is on "shiftwidth" value takes effect at starting of lines
tabstop_size=2

# Useful for "ts" option
# Not clear (see :help softtabstop)
softtabstop_size=0

# 1. Number of spaces to insert when hitting <Tab> in start of line
#    Takes effect only if smarttab to be on else only "2" is in effect.
# 2. Number of spaces to insert when shifting (see shift-left-right)
shiftwidth_size=2


# Configuration used
tab_to_space_config="set \
                      tabstop=$tabstop_size \
                      softtabstop=$softtabstop_size \
                      shiftwidth=$shiftwidth_size \
                      expandtab
                     "

# TODO vim_version_8 function

VIMRC="$HOME/.vimrc"
write_to_file $VIMRC "$defaults_addition"
append_to_file $VIMRC "\n$tab_to_space_config"
echo "Vim configuration for 'tab to spaces' successful!"
