#! /bin/bash
# Script that customises Vim for personal needs
# Currently it sets functionality for converting tab to spaces
#
# Usage: {script-name}

. common-script

# Recommended  addition to .vimrc
# Due to presence of defaults.vim
# See ":help defaults.vim"
# Doesn't work for version less than 8
DEFAULTS_ADDITION='unlet! skip_defaults_vim\nsource $VIMRUNTIME/defaults.vim'

# Variables for configuration
# Number of space to insert when hitting <Tab> in all places
# If smarttab is on "shiftwidth" value takes effect at starting of lines
TABSTOP_SIZE=2

# Useful for "ts" option
# Not clear (see :help softtabstop)
SOFTTABSTOP_SIZE=0

# 1. Number of spaces to insert when hitting <Tab> in start of line
#    Takes effect only if smarttab to be on else only "2" is in effect.
# 2. Number of spaces to insert when shifting (see shift-left-right)
SHIFTWIDTH_SIZE=2


# Configuration used
tab_to_space_config="set \
                      tabstop=$TABSTOP_SIZE \
                      softtabstop=$SOFTTABSTOP_SIZE \
                      shiftwidth=$SHIFTWIDTH_SIZE \
                      expandtab
                     "

# TODO vim_version_8 function

VIMRC="$HOME/.vimrc"

# Debug
# set -x

# Check if user is ROOT and notify if he is.
if root_check && [ "$1" != 'root' ]
then
  error 'You are executing this script as root.\nTo override pass root as first argument.\nAborting'
else
  write_to_file $VIMRC "$DEFAULTS_ADDITION"
  append_to_file $VIMRC "\n$tab_to_space_config"
  echo "Vim configuration for 'tab to spaces' successful!"
fi
