#!/bin/bash
# Script used to toggle the Touchpad
# state on or off using 'synclient'
# 'synclient' presence assumed

touchpad_current_state=`synclient -l | grep 'TouchpadOff' | awk '{ print $3 }'`

# Toggle touchpad state
if [ $touchpad_current_state -eq 0 ]
then
  synclient 'TouchpadOff=1'
else
  synclient 'TouchpadOff=0'
fi
