#! /bin/bash
# Script that installs essential packages through apt package manager
#
# Usage: {script-name}

# source: https://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

. $DIR/../lib/common-script

dict_packages='dict dict-gcide dict-wn'
essential_packages="$dict_packages git vim zeal gparted tlp pm-utils g++ keepassxc terminator diodon"
optional_packages='thunderbird syncthing git-email pidgin vlc meld simplescreenrecorder'

info 'Package installation initiated ..'
echo 'The current list of ESSENTIAL packages are:'
for package in $essential_packages
do
  echo '* '"$package"
done

packages_to_install="$essential_packages"

# Get the preference for optional packages
echo # Kept for new-line (side-effect)
echo 'Choose the optional packages to install:'

for package in $optional_packages
do
  while true
  do
    echo -n "Do you want to install '$package' [y/n]: "
    read yn
    case $yn in
      [Yy]*)
        optional_packages_to_install+=" $package"
        break
        ;;
      [Nn]*)
        break
        ;;
      *)
        echo 'Please answer yes or no.'
        ;;
    esac
  done
done

packages_to_install+="$optional_packages_to_install"

echo # Kept for new line (side-effect)
notify 'Installing the following packages:'
for package in $packages_to_install
do
  echo '* '"$package"
done

# check if user is root and execute command accordingly
if root_check
then
  for package in $packages_to_install
  do
    apt install --asume-yes $package
  done
else
  for package in $packages_to_install
  do
    sudo apt install --assume-yes $package
  done
fi

info 'Package installation terminated.'
